dd_collector/accounts/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.contrib import admin
from accounts.forms import PasswordResetForm, SetPasswordForm

from . import views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^create-api-key$', views.create_api_key, name='create-api-key'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
    url(r'^create-subscription$',  views.create_subscription, name='create_subscription'),
    url(r'^update-api-key/(?P<pk>.+)$', views.update_api_key, name='update_api_key'),
    url(r'^delete-api-key/(?P<pk>.+)$', views.delete_api_key, name='delete_api_key'),
    url(r'^accounts/', include('allauth.urls')),
    url(
        r'^login/$',
        auth_views.LoginView.as_view(
            template_name='accounts/login.html', redirect_authenticated_user=True),
        name='login',
    ),
    url(r'^signup', views.sign_up, name='signup'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),
    url(r'^edit/$', views.profile, name='edit'),
    url(r'^edit/change-password/$', views.change_password, name='change_password'),
    # Password reset
    url(
        r'^password-reset/$',
        auth_views.PasswordResetView.as_view(
            template_name='accounts/password_reset.html'),
        name='password_reset'
    ),
    url(r'^password_reset/done/$',
        auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'), name='password_reset_done'),
    url(
        r'^password-reset-confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html'),
        name='password_reset_confirm',
    ),
    url(r'^password-reset-complete/$', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),
        name='password_reset_complete'),
    url(r'^dashboard$', views.dashboard, name='home'),
    url('^$', views.index, name='index'),
    url(r'^cancel-subscription$', views.cancel_subscription, name='cancel_subscription'),
    url(r'^contact-us$', views.contact_us, name='contact_us'),
    url(r'^test-products$', views.test_products, name='test_products'),
    url(r'^device-info$', views.device_info, name='device_info'),
    url(r'^geodata-info$', views.geodata_info, name='geodata_info'),
    url(r'^comprehensive-info', views.comprehensive_info, name='comprehensive_info'),
    url(r'^plans-pricing/$', views.plans_pricing, name='plans_pricing'),
    url(r'^licencing/$', views.licencing, name='licencing'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^subscribing/$', views.subscribing, name='subscribing'),
    url(r'^documentation/rest_api/$', views.rest_api, name='rest_api'),
    url(r'^documentation/authentication/$', views.authentication, name='authentication'),
    url(r'^documentation/quickstart/$', views.quickstart, name='quickstart'),
    url(r'^documentation/tracking_service/$', views.tracking_service, name='tracking_service'),
    url(r'^documentation/geodata_service/$', views.geodata_service, name='geodata_service'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

dd_collector/accounts/forms.py
import re
from django import forms
from django.core.exceptions import ValidationError

from django.contrib.auth import forms as auth_forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.tokens import default_token_generator
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.utils.translation import ugettext_lazy as _
from django_countries.fields import CountryField

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit
from accounts.emails import send_password_reset
from accounts.models import User
from accounts.choices import (
    INDUSTRY_CHOICES, COUNTRY_COICES, COUNTRY_COICES_ISO)


class GeodataForm(forms.Form):
    country = forms.ChoiceField(
        choices=COUNTRY_COICES_ISO, label='Country', required=True)
    city = forms.CharField(max_length=20, label='City')
    address = forms.CharField(max_length=255, label='Address')
    radius = forms.CharField(
        max_length=255, label='Radiuses with comma: "r1,r2,r3"',
        required=False)


class ContactUsForm(forms.Form):
    first_name = forms.CharField(
        widget=forms.TextInput, label='First Name', required=True)
    last_name = forms.CharField(
        widget=forms.TextInput, label='Last Name', required=True)
    job_title = forms.CharField(
        widget=forms.TextInput, label='Job Title', required=True)
    email = forms.EmailField(widget=forms.EmailInput,
                             label='Professional E-mail', required=True)
    phone = forms.CharField(widget=forms.TextInput,
                            label='Phone', required=True)
    company = forms.CharField(widget=forms.TextInput,
                              label='Company', required=True)
    industry = forms.ChoiceField(
        choices=INDUSTRY_CHOICES, label='What primary industry do you serve?',
        required=True)
    country = forms.ChoiceField(
        choices=COUNTRY_COICES, label='Country', required=True)
    text = forms.CharField(widget=forms.Textarea(
        attrs={"rows": 5, "cols": 20}), label='How Can We Help?',
        required=True)


class PasswordResetForm(auth_forms.PasswordResetForm):
    helper = FormHelper()
    helper.form_class = 'login-form'
    helper.layout = Layout(
        'email',
        Submit('submit', _('Reset my password'))
    )

    # pylint: disable=arguments-differ
    def save(self, *args, **kwargs):
        """
        Generates a one-use only link for resetting password and sends to the
        Copy of Django's implementation, changed to use our own email-sending.
        """
        user_model = get_user_model()
        email = self.cleaned_data["email"]
        active_users = user_model.objects.filter(
            email__iexact=email, is_active=True)
        for user in active_users:
            # Make sure that no email is sent to a user that actually has
            # a password marked as unusable
            if not user.has_usable_password():
                continue

            uid = urlsafe_base64_encode(force_bytes(user.pk))
            token = default_token_generator.make_token(user)
            send_password_reset(user, uid, token)


class SetPasswordForm(auth_forms.SetPasswordForm):
    helper = FormHelper()
    helper.form_class = 'login-form'
    helper.layout = Layout(
        'new_password1',
        Submit('submit', _('Change my password'))
    )

    def __init__(self, user, *args, **kwargs):
        super(SetPasswordForm, self).__init__(user, *args, **kwargs)

        del self.fields['new_password2']


class ChangePasswordForm(forms.ModelForm):
    class Meta:
        model = User
        fields = []

    password_old = forms.CharField(widget=forms.PasswordInput(),
                                   label=_(
                                       "Enter your old password for confirmation"),
                                   required=True)
    password_new = forms.CharField(
        widget=forms.PasswordInput(), label=_("New password"), required=True)

    helper = FormHelper()
    helper.layout = Layout(
        'password_old',
        'password_new',
        Submit('submit', _('Save changes'), css_class="btn btn-primary")
    )

    def clean(self):
        cleaned_data = super(ChangePasswordForm, self).clean()
        password_old = cleaned_data.get('password_old')
        self.password_new = cleaned_data.get('password_new')

        # If either old or new password is None, then we get an inline error and don't want to raise ValidationError
        if password_old and self.password_new and not self.instance.check_password(password_old):
            raise forms.ValidationError(
                _("The old password you've entered is not correct!"))

        return cleaned_data

    def save(self, commit=True):
        self.instance.set_password(self.password_new)

        return super(ChangePasswordForm, self).save(commit)


class SignUpForm(UserCreationForm):
    name = forms.CharField(max_length=30, required=False,
                           help_text='Optional.')
    email = forms.EmailField(
        max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('name', 'email')


class UserEditForm(forms.Form):
    avatar = forms.ImageField(label='', required=False)
    name = forms.CharField(max_length=255, required=True)
    email = forms.EmailField(required=False)


class RequestForm(forms.Form):
    city = forms.CharField(label='City', max_length=128, required=False)
    country = CountryField(blank=True).formfield()
    address = forms.CharField(label='Address', max_length=128, required=False)
    email = forms.EmailField(label='E-mail', max_length=128, required=False)
    phone_number = forms.CharField(
        help_text="example : +44 1632 960070",
        label='Phone number', max_length=20, required=False)

    # [extending form method for custom validation]
    def clean(self):
        regex = "[+]\d"

        cd = self.cleaned_data
        phone_number = cd.get('phone_number')
        address = cd.get('address')
        city = cd.get('city')
        country = cd.get('country')

        # [phohe number validation]
        if phone_number and not re.search(regex, phone_number):
            raise ValidationError('Invalid phone number')

        # [address validation]
        if address and not city or not country:
            raise ValidationError(
                'You have to complete Country and City if you completed Address')

        return cd

dd_collector/templates/includes/edit_profile_form.html
{% load crispy_forms_tags widget_tweaks %}
{% load crispy_forms_field %}
{% load form_tags %}
{% if edit_form.non_field_errors %}
<div class="alert alert-danger" role="alert">
    {% for error in edit_form.non_field_errors %}
    <p{% if forloop.last %} class="mb-0 red"{% endif %}>{{ error }}</p>
    {% endfor %}
</div>
{% endif %}
<div class="padding-top-none modal-body ">
    <div class="form-group">
        <form method="POST" enctype="multipart/form-data" class="form_disabled js-edit-profile" id="formEditProfile">
            {% csrf_token %}
            <div class="row">
                <div class="text-center background-image">
                    {% if request.user.avatar %}
                        <img src="{{MEDIA_URL}}/{{request.user.avatar}}" class="img-circle border"  name="suka_avatar" height="200px" width="200px"  alt="avatar"> 
                    {% else %}
                        <img src="http://placehold.it/60/30a5ff/fff" class="img-circle"  name="suka_avatar"  height="200px" width="200px" alt="">
                    {% endif %}
                    <div class="pd-t-3 text-center">
                        <label for="id_avatar" class="btn btn-default" id="disable" >
                        <i class="fa fa-pencil" aria-hidden="true" style="font-size: 14px"></i>
                        {{ edit_form.avatar }}
                        </label>
                    </div>
                </div>
            </div>
            {% for field in edit_form %} 
                {{field.label_tag}}
                <div class="{% if field.errors %} has-error {% endif %} pd-t-3">
                    {% render_field field|add_class:'form-control my-input' class=field|input_class  %}
                </div>
                {% for error in field.errors %}
                    <div class="invalid-feedback help-block {% if field.errors %} has-error {% endif %}">
                        <span class="text-danger">{{ error }}</span>
                        {% if field.help_text %}
                            <small class="form-text text-muted">
                                {{ field.help_text|safe }}
                            </small>
                        {% endif %}
                    </div>
                {% endfor %}
            {% endfor %} 
            <div class="text-right" style="margin-top:30px">
                <hr/>
                <button type="submit" class="btn btn-primary">Save</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </form>
    </div>
</div>

dd_collector/templates/includes/form.html
{%load static %}
{% load form_tags widget_tweaks %}

{% if form.non_field_errors %}
  <div class="alert alert-danger" role="alert">
    {% for error in form.non_field_errors %}
      <p{% if forloop.last %} class="mb-0 red"{% endif %}>{{ error }}</p>
    {% endfor %}
  </div>
{% endif %}

{% for field in form %} 
  <div class="form-group">
    {{ field.label_tag }}
    {% render_field field|add_class:'form-control my-input' class=field|input_class  %}
    {% for error in field.errors %}
      <div class="invalid-feedback help-block red">
        {{ error }}
      </div>
    {% endfor %}
    {% if field.help_text %}
      <small class="form-text text-muted">
        {{ field.help_text|safe }}
      </small>
    {% endif %}
  </div>
{% endfor %}

dd_collector/templates/includes/password_change_form.html
{% load crispy_forms_tags widget_tweaks %}
{% load crispy_forms_field %}
{% load form_tags %}
{% load i18n %}
{% if password_form.non_field_errors %}
   <div class="alert alert-danger" role="alert">
      {% for error in password_form.non_field_errors %}
      <p{% if forloop.last %} class="mb-0 red"{% endif %}>{{ error }}</p>
      {% endfor %}
   </div>
{% endif %}
<div class="padding-top-none modal-body ">
   <div class="form-group" style="padding-top:25px;">
      <form action='{% url "change_password" %}' method="POST" class='js-change-password'>
         {% csrf_token %}
         {% for field in password_form %} 
            <div class="form-group">
               {{field.label_tag}}
               <div class="{% if field.errors %} has-error {% endif %}">
                  {% render_field field|add_class:'form-control my-input' class=field|input_class %}
               </div>
               {% if field.html_name == "new_password1" %}
                  <small class="form-text text-muted">
                     <ul style='padding:0; margin: 10px 0 0 15px;'>
                        <li>Your password can't be too similar to your other personal information.</li>
                        <li>Your password must contain at least 8 characters.</li>
                        <li>Your password can't be a commonly used password.</li>
                        <li>Your password can't be entirely numeric.</li>
                     </ul>
                  </small>
               {% endif %}
                  {% for error in field.errors %}
                     <div class="invalid-feedback help-block {% if field.errors %} has-error {% endif %}">
                        <span class="text-danger">{{ error }}</span>
                        {% if field.help_text %}
                           <small class="form-text text-muted">
                              {{ field.help_text|safe }}
                           </small>
                        {% endif %}
                     </div>
                  {% endfor %}
            </div>
         {% endfor %} 
         <div class="text-right" style="margin-top:30px">
            <hr/>
            <button type="submit" class="btn btn-primary">Save</button>
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
         </div>
      </form>
   </div>
</div>

dd_collector/templates/includes/signup_form.htm
{% load form_tags widget_tweaks %}
{% if form.non_field_errors %}
<div class="alert alert-danger" role="alert">
   {% for error in form.non_field_errors %}
   <p{% if forloop.last %} class="mb-0"{% endif %}>{{ error }}</p>
   {% endfor %}
</div>
{% endif %}
{% for field in form %}
<div class="form-group">
   {{ field.label_tag }}
   {% render_field field class=field|input_class %}
   {% for error in field.errors %}
   <div class="invalid-feedback">
      {{ error }}
   </div>
   {% endfor %}
   {% if field.help_text %}
   <small class="form-text text-muted">
   {{ field.help_text|safe }}
   </small>
   {% endif %}
</div>
{% endfor %}

dd_collector/templates/includes/success-api-key.html
<h2 style='color: rgb(48, 57, 64); font-size: 34px; font-weight: 500; line-height: 41px; margin-top: 65px;' class='text-center'>Here's Your Secret API Key</h2>
<p style='font-size:16px; line-height:23px; color:#333; font-weight:normal' class='text-center'>We only show this to you once (right now).</p>
<p style='font-size:16px; line-height:23px; color:#333; font-weight:normal' class='text-center'>If you forget it, you'll need to generate a new one.</p>
<input style="line-height: 22px; color: #4F4F4F; font-size: 18px; font-weight: 500; background-color: #F2F2F2; width:100%; margin-top: 38px;  padding: 10px 5%; outline: none; display: block; border:none; border-radius: 5px; margin-bottom: 12px; font-family:'Montserrat', sans-serif; height: 50px;" id='copy-api-key' class='form-control' readonly="readonly" value="{{apiKey}}"}>
<h5 id='to-copy-text' class='text-center' style='color:green; display:none'>Copied!</h5>
<button id="close-success-api-key" type="button" style="line-height: 22px; margin-left:auto; box-sizing: border-box; align-items: center; box-shadow: none; color: #fff; text-align: center; font-size: 18px; font-weight: 500; background-color: #2F80ED; width: 165px; padding: 0 10px; transform: translateZ(0px); justify-content: center; outline: none; text-decoration: none; display: flex; margin-top: 28px; margin-bottom:30px; border-radius: 5px; font-family: 'Montserrat', sans-serif; height: 42px;">
        Close
</button>

<style>
    #copy-api-key::selection {
  background-color: rgba(0,0,0,0);
}
</style>

<script>
    $(function() {
        $('#copy-api-key').click(function() {
            $(this).select();
            document.execCommand('copy');
            $('#to-copy-text').css('display', 'block');
        })
        var closeSuccessApiKey = function(){ 
            location.reload();
        };
        $('#close-success-api-key').click(closeSuccessApiKey);
    })
</script>