dd_collector/accounts/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.contrib import admin
from accounts.forms import PasswordResetForm, SetPasswordForm

from . import views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^create-api-key$', views.create_api_key, name='create-api-key'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
    url(r'^create-subscription$',  views.create_subscription, name='create_subscription'),
    url(r'^update-api-key/(?P<pk>.+)$', views.update_api_key, name='update_api_key'),
    url(r'^delete-api-key/(?P<pk>.+)$', views.delete_api_key, name='delete_api_key'),
    url(r'^accounts/', include('allauth.urls')),
    url(
        r'^login/$',
        auth_views.LoginView.as_view(
            template_name='accounts/login.html', redirect_authenticated_user=True),
        name='login',
    ),
    url(r'^signup', views.sign_up, name='signup'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),
    url(r'^edit/$', views.profile, name='edit'),
    url(r'^edit/change-password/$', views.change_password, name='change_password'),
    # Password reset
    url(
        r'^password-reset/$',
        auth_views.PasswordResetView.as_view(
            template_name='accounts/password_reset.html'),
        name='password_reset'
    ),
    url(r'^password_reset/done/$',
        auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'), name='password_reset_done'),
    url(
        r'^password-reset-confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html'),
        name='password_reset_confirm',
    ),
    url(r'^password-reset-complete/$', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),
        name='password_reset_complete'),
    url(r'^dashboard$', views.dashboard, name='home'),
    url('^$', views.index, name='index'),
    url(r'^cancel-subscription$', views.cancel_subscription, name='cancel_subscription'),
    url(r'^contact-us$', views.contact_us, name='contact_us'),
    url(r'^test-products$', views.test_products, name='test_products'),
    url(r'^device-info$', views.device_info, name='device_info'),
    url(r'^geodata-info$', views.geodata_info, name='geodata_info'),
    url(r'^comprehensive-info', views.comprehensive_info, name='comprehensive_info'),
    url(r'^plans-pricing/$', views.plans_pricing, name='plans_pricing'),
    url(r'^licencing/$', views.licencing, name='licencing'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^subscribing/$', views.subscribing, name='subscribing'),
    url(r'^documentation/rest_api/$', views.rest_api, name='rest_api'),
    url(r'^documentation/authentication/$', views.authentication, name='authentication'),
    url(r'^documentation/quickstart/$', views.quickstart, name='quickstart'),
    url(r'^documentation/tracking_service/$', views.tracking_service, name='tracking_service'),
    url(r'^documentation/geodata_service/$', views.geodata_service, name='geodata_service'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

dd_collector/accounts/models.py
# -*- coding: utf-8 -*-
from django.contrib.auth.models import (
    AbstractBaseUser, BaseUserManager, PermissionsMixin)
from django.db import models
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _
from djmoney.models.fields import MoneyField
from django.conf import settings
from django.db.models.signals import post_save, post_delete
import stripe
from rest_framework_api_key.models import AbstractAPIKey


stripe.api_key = settings.STRIPE_SECRET_KEY


class UserManager(BaseUserManager):
    # Mostly copied from django.contrib.auth.models.UserManager

    def _create_user(self, email, password,
                     is_staff, is_superuser, **extra_fields):
        """
        Creates and saves a User with the given username, email and password.
        """
        now = timezone.now()
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email,
                          is_staff=is_staff, is_active=True,
                          is_superuser=is_superuser, last_login=now,
                          date_joined=now, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email=None, password=None, **extra_fields):
        return self._create_user(email, password, False, False,
                                 **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        return self._create_user(email, password, True, True,
                                 **extra_fields)


class User(PermissionsMixin, AbstractBaseUser):
    email = models.EmailField(_('email address'), max_length=254, unique=True)
    name = models.CharField(max_length=255)
    avatar = models.ImageField(upload_to="avatars", blank=True)

    is_staff = models.BooleanField(
        _('staff status'), default=False)
    is_active = models.BooleanField(
        _('active'),  default=True)
    date_joined = models.DateTimeField(
        _('date joined'), null=True, blank=True, default=timezone.now)

    USERNAME_FIELD = 'email'

    objects = UserManager()

    def get_full_name(self):
        return self.name

    def get_short_name(self):
        return self.name


class Customer(models.Model):
    stripe_customer_id = models.CharField(max_length=100)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    is_waiting_custom = models.BooleanField(
        verbose_name="Customer is waiting for an answer about custom plan", default=False)
    updated_at = models.DateTimeField(auto_now=True)
    address = models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    state = models.CharField(max_length=100)
    zip = models.CharField(max_length=100)
    country = models.CharField(max_length=100)

    def __str__(self):
        return self.stripe_customer_id

    class Meta:
        verbose_name = 'Customer'
        verbose_name_plural = 'Customers'


# POST_SAVE signal for creating Stripe-Customer object
def post_save_customer_create(sender, instance, created, *args, **kwargs):
    if created:
        Customer.objects.get_or_create(user=instance)

    customer, created = Customer.objects.get_or_create(user=instance)

    if customer.stripe_customer_id is None or customer.stripe_customer_id == '':
        new_customer_id = stripe.Customer.create(
            email=instance.email, name=instance.name)
        customer.stripe_customer_id = new_customer_id['id']
        customer.save()


post_save.connect(post_save_customer_create, sender=settings.AUTH_USER_MODEL)


# POST_DELETE signal for deleting Stripe-Customer object
def post_delete_customer(sender, instance, using, *args, **kwargs):
    try:
        stripe.Customer.delete(instance.stripe_customer_id)
    except stripe.error.InvalidRequestError:
        pass


post_delete.connect(post_delete_customer, sender=Customer)


class Product(models.Model):
    stripe_product_id = models.CharField(max_length=100, null=True, blank=True)
    description = models.TextField()
    active = models.BooleanField(default=True)
    name = models.CharField(max_length=150, db_index=True)

    TYPE_CHOICES = (
        ('service', 'Service'),
        ('good', 'Good')
    )

    type = models.CharField(
        max_length=10, choices=TYPE_CHOICES, default='service')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return '{}'.format(self.name)

    class Meta:
        verbose_name = 'Product'
        verbose_name_plural = 'Products'


# POST_SAVE signal for creating Stripe-Product object
def post_save_product_create(sender, instance, created, *args, **kwargs):
    if instance.stripe_product_id is None or instance.stripe_product_id == '':
        product_stripe = stripe.Product.create(description=instance.description,
                                               active=instance.active,
                                               name=instance.name,
                                               type=instance.type)
        instance.stripe_product_id = product_stripe['id']
        instance.save()


post_save.connect(post_save_product_create, sender=Product)


# POST_DELETE signal for deleting Stripe-Product object
def post_delete_product(sender, instance, using, *args, **kwargs):
    try:
        stripe.Product.delete(instance.stripe_product_id)
    except stripe.error.InvalidRequestError:
        pass


post_delete.connect(post_delete_product, sender=Product)


class Plan(models.Model):
    stripe_plan_id = models.CharField(max_length=100, blank=True, null=True)
    INTERVAL_CHOICES = (
        ('day', 'Day'),
        ('week', 'Week'),
        ('month', 'Month'),
        ('year', 'Year')
    )
    interval = models.CharField(max_length=5, choices=INTERVAL_CHOICES)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    active = models.BooleanField(default=True)
    nickname = models.CharField(max_length=50)
    created = models.DateTimeField(auto_now_add=True)
    price = MoneyField(max_digits=14, decimal_places=2, default_currency='USD')

    def __str__(self):
        return self.nickname

    class Meta:
        verbose_name = 'Plan'
        verbose_name_plural = 'Plans'


class PlanItems(models.Model):
    plan = models.ForeignKey(
        Plan, related_name='plan_items', on_delete=models.CASCADE)
    value = models.CharField(max_length=150)

    class Meta:
        verbose_name = 'Plan item'
        verbose_name_plural = 'Plan items'

    def __str__(self):
        return self.plan.nickname + ' ' + self.value


# POST_SAVE signal for creating Stripe-Plan object
def post_save_plan_create(sender, instance, created, *args, **kwargs):
    if instance.stripe_plan_id is None or instance.stripe_plan_id == '':
        plan_stripe = stripe.Plan.create(currency=instance.price.currency,
                                         amount=int(instance.price.amount)*100,
                                         active=instance.active,
                                         product=instance.product.stripe_product_id,
                                         interval=instance.interval)

        instance.stripe_plan_id = plan_stripe['id']
        instance.save()


post_save.connect(post_save_plan_create, sender=Plan)


# POST_DELETE signal for deleting Stripe-Plan object
def post_delete_plan(sender, instance, using, *args, **kwargs):
    try:
        stripe.Plan.delete(instance.stripe_plan_id)
    except stripe.error.InvalidRequestError:
        pass


post_delete.connect(post_delete_plan, sender=Plan)


class Subscription(models.Model):
    stripe_subscription_id = models.CharField(
        max_length=100, blank=True, null=True)
    stripe_customer_id = models.ForeignKey(
        Customer, verbose_name='Customer', on_delete=models.CASCADE)
    is_active = models.BooleanField(default=False)
    plan_type = models.ForeignKey(Plan, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    trial_end = models.IntegerField()

    def __str__(self):
        return self.stripe_subscription_id

    class Meta:
        verbose_name = 'Subscription'
        verbose_name_plural = 'Subscriptions'


# POST_SAVE signal for creating Stripe-Subscription object
def post_save_subscription_create(sender, instance, created, *args, **kwargs):
    if instance.stripe_subscription_id is None or instance.stripe_subscription_id == '':
        subscription_stripe = stripe.Subscription.create(items=[{"plan": instance.plan_type.stripe_plan_id}],
                                                         customer=instance.stripe_customer_id.stripe_customer_id,
                                                         trial_end=instance.trial_end)
        instance.stripe_subscription_id = subscription_stripe['id']
        instance.save()


post_save.connect(post_save_subscription_create, sender=Subscription)


# POST_DELETE signal for deleting Stripe-Subscription object
def post_delete_subscription(sender, instance, using, *args, **kwargs):
    try:
        stripe.Subscription.delete(instance.stripe_subscription_id)
    except stripe.error.InvalidRequestError:
        pass


post_delete.connect(post_delete_subscription, sender=Subscription)


class UserApiKey(AbstractAPIKey):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE, related_name='api_keys')

    class Meta:
        verbose_name = 'api key'
        verbose_name_plural = 'api keys'


class SubscribedEmails(models.Model):
    email = models.EmailField(unique=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.email

    class Meta:
        verbose_name = 'Subscribed E-mail'
        verbose_name_plural = 'Subscribed E-mails'

dd_collector/templates/accounts/contact_us.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags widget_tweaks %}
{% load crispy_forms_field %}
{% load form_tags %}
{% load split_api_key %}
{% block content %}
    <div class='col-sm-12'>
        <div class="row">
            <div class="col-sm-5">
                <h1 class='text-center'>Contact Us</h1>
                <div class='panel panel-default'>
                    <div class="panel-body">
                        <form method='POST' id='contact-us-form'>
                            {% csrf_token %}
                            {% include 'includes/form.html' %}
                            <div class='text-center'><button type='submit' class='btn btn-primary'>Send Request</button></div>
                        </form>
                    </div>
                </div>
            </div>
        <div class='col-sm-1'></div>
        <div class="col-sm-6" style='height:100%'>
            <h1 class='text-center' style='color:#30a5ff; font-size:4rem; font-weight:700;'>Let’s chat.</h1>
            <div class="panel">
                <div class="panel-body">
            <div class='text-center' style='font-size: 2rem'>
                <p style='color:black; margin-top:30px;'>If you’re considering DadaDriven or just need</p>
                <p style='color:black'>more information, we can help. Please fill out</p>
                <p style='color:black'>this form and we’ll contact you soon.</p>
                <br>
                <p style='color:black'>Or send an email to <strong>team@datadriven.com</strong></p>
            </div>
        </div>
        </div>
        </div>  
        </div>
    </div>
{% endblock %}

dd_collector/templates/accounts/device_info.html
{% extends 'accounts/test_products.html' %}



{% block content %}
<script
    type="text/javascript"
    src="https://richy.ddriven.eu/assets/tracking.js">
</script>
<div class="row">
        <div class="col-sm-6">
            <h1>Device Info</h1>
    </div>
</div>
<div>
    <table class="table table-bordered" width="90%" id='device_info_table' action="{% url 'device_info' %}" >
        <input type="hidden" id='csrf' name='csrfmiddlewaretoken' value='{{ csrf_token }}'>
        {% for k in components %}
            {% if k.key != 'canvas' and k.key != 'webgl' %}
                <tr>
                    <td><strong>{{ k.key }}</strong></td>
                    <td>{{ k.value }}</td>
                </tr>
            {% endif %}
        {% endfor %}
        {% if launch %}
            <tr>
                <td><strong>Device Age</strong></td>
                <td>{{ launch }}</td>
            </tr>
        {% else %}
            <tr>
                <td><strong>Device Age</strong></td>
                <td>UNKNOWN</td>
            </tr>
        {% endif %}
        {% if attr %}
            <tr>
                <td><strong>Price</strong></td>
                <td>{% for a in attr%}{{a.price.amount}} {{a.price.currency}}<br>{% endfor %}</td>
            </tr>
        {% else %}
            <tr>
                <td><strong>Price</strong></td>
                <td>UNKNOWN</td>
            </tr>
        {% endif %}
    </table>  
  </div>
{% endblock %}



{% block javascript %}
<script src='https://cdn.jsdelivr.net/npm/fingerprintjs2@2.1.0/fingerprint2.js'></script>
<script>
    var config = {
        'accountId': 'b86cdf1f-91a9-4d40-bc61-fdb8ed5062a0',
        'sessionId': '{{sessionId}}',
        'userId': '{{user_id}}',
        'pageTitle': 'Application Form 1',
        'fields': {
            'LoginFormField': 'login-form-field',
        },
    };
    da('config', config);
</script>

<script>

var bool = true;
if (window.requestIdleCallback) {
    requestIdleCallback(function () {
       Fingerprint2.get(function (components) {

        if (bool === true){
            var data = {'components': JSON.stringify(components), 'csrfmiddlewaretoken': $('#csrf').val()}
                $.ajax({
                    url: $('#device_info_table').attr('action'),
                    data: data,
                    type: "post",
                    dataType: "json",
                    success: function(data) {
                        if (data.is_valid) {
                            $('body').html(data.device_info);
                            bool = false;
                        }
                        else{
                            alert(2);
                            location.reload();
                        }
                    }
                });}
       })
    })
 } else {
    setTimeout(function () {
       Fingerprint2.get(function (components) {
       })  
    }, 500)
 }
</script>

{% endblock %}

dd_collector/templates/accounts/geodata_info.html
{% extends 'accounts/test_products.html' %}

{% block content %}
<div class="row">
    <div class="col-sm-6">
        <h1>Geodata</h1>
        <div class='panel panel-default'>
            <div class="panel-body">
                <form method='POST'>
                    {% csrf_token %}
                    {% include 'includes/form.html' %}
                    <div class='text-center'><button type='submit' class='btn btn-primary'>Send Request</button></div>
                </form>
            </div>
        </div>
    </div>
</div>
<div>
  <table class="table table-bordered" width="90%">
    {% for k,v in response.items %}
    <tr>
      <td>{{ k }}</td>
      <td>{{ v }}</td>
    </tr>
    {% endfor %}
  </table>  
</div>
{% endblock %}

dd_collector/templates/accounts/password_reset_complete.html
{% extends "accounts/signup.html" %}

{% load i18n %}
{% load crispy_forms_tags %}


{% block signupbackground %}
    <h1 class='text-center mt-4' style='font-weight:600; font-size:1.3rem; line-height:1.75rem; color: black;'>{% trans "PASSWORD RESET COMPLETE" %}</h1>

    <p class='text-center mt-4' style='font-size: 1rem; line-height:1.5rem'>
        {% trans 'Your password has been set. You may go ahead and log in now.' %}
    </p>
    <p class="text-center">
        <br>
        <a href="{% url 'login' %}" class="btn btn-primary" style='display:block; width:100%; background-color:#34A3FB; border-color:#34A3FB; border-radius:5px; line-height:1.375rem; font-size: 1.125remrem; padding:6px 30px;'>{% trans "Log in" %}</a>
    </p>
{% endblock %}

dd_collector/templates/accounts/profile.html
{% extends 'base.html'%} {% load static %} {% load i18n %} {% load
crispy_forms_tags widget_tweaks %} {% load crispy_forms_field %} {% load
form_tags %} {% block content %}
<div class="row">
    <div class="row" style="margin:0;">
        <div class="col-lg-12" style="padding-left:10px;">
            <h1
                style="font-weight:500; font-style:normal; font-size: 43px; line-height:52px; margin-bottom:30px;"
            >
                Profile
            </h1>
        </div>
    </div>
    <div class="col-md-6 col-lg-4" id="profile-div">
        <div
            class="profile-left"
            style="
        background-color: #fff;
                               "
        >
            <!-- PROFILE HEADER -->
            <div class="profile-header">
                <div class="overlay"></div>
                <div class="profile-main">
                    {% if request.user.avatar %}
                    <img
                        src="{{MEDIA_URL}}/{{request.user.avatar}}"
                        class="img-circle"
                        height="200px"
                        width="200px"
                        alt="avatar"
                    />
                    {% else %}
                    <img
                        src="http://placehold.it/60/30a5ff/fff"
                        class="img-circle"
                        height="200px"
                        width="200px"
                        alt=""
                    />
                    {% endif %}
                    <h3 class="name">{{request.user.name}}</h3>
                    <span class="online-status status-available">Online</span>
                </div>
                <div class="profile-stat">
                    <div class="row">
                        <div class="col-sm-4 stat-item">
                            <span>45</span><span>Projects</span>
                        </div>
                        <div class="col-sm-4 stat-item">
                            <span>15</span> <span>Awards</span>
                        </div>
                        <div class="col-sm-4 stat-item">
                            <span>2174</span><span>Points</span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="profile-detail">
                <div class="profile-info">
                    <ul class="list-unstyled list-justify">
                        <li
                            class="rows"
                            style="
                              border-bottom: 1px solid #F2F2F2;
                              height: 48px;
                              padding: 0 20px;
                              margin: 0;
                              display: flex;
                              justify-content: space-between;
                              align-items: center;
                              "
                        >
                            <strong>Date joined :</strong
                            ><span>{{request.user.date_joined}}</span>
                        </li>
                        <li
                            class="rows"
                            style="
                              border-bottom: 1px solid #F2F2F2;
                              height: 48px;
                              padding: 0 20px;
                              margin: 0;
                              display: flex;
                              justify-content: space-between;
                              align-items: center;
                              "
                        >
                            <strong>Last login :</strong>
                            <span>{{request.user.last_login}}</span>
                        </li>
                        <li
                            class="rows"
                            style="
                              border-bottom: 1px solid #F2F2F2;
                              height: 48px;
                              padding: 0 20px;
                              margin: 0;
                              display: flex;
                              justify-content: space-between;
                              align-items: center; 
                              "
                        >
                            <strong>Email :</strong>
                            <span>{{request.user.email}}</span>
                        </li>
                        <li
                            class="rows"
                            style="
                              border-bottom: 1px solid #F2F2F2;
                              height: 48px;
                              padding: 0 20px;
                              margin: 0;
                              display: flex;
                              justify-content: space-between;
                              align-items: center;
                              "
                        >
                            <strong>Website :</strong>
                            <span
                                ><a href="{{current_site}}"
                                    >{{current_site}}</a
                                ></span
                            >
                        </li>
                    </ul>
                </div>
                <div
                    class="text-center"
                    style="
                     display: flex;
                     justify-content: space-between;
                     padding: 35px 34px 32px"
                >
                    <button
                        type="button"
                        class="btn"
                        data-toggle="modal"
                        data-target="#changePasswordModal"
                        data-whatever="@fat"
                        style="
                           margin-right:5px; 
                           border: 1.5px solid #BDBDBD;
                           background: #fff;
                           color: #828282;
                           height: 45px;
                           width: 145px;
                           text-align: center;
                           padding-right: 6px;
                           padding-left: 6px;"
                    >
                        Change Password
                    </button>
                    <button
                        type="button"
                        class="btn "
                        data-toggle="modal"
                        data-target="#exampleModal"
                        data-whatever="@fat"
                        style="
                           margin-left:5px; 
                           background: #2F80ED;
                           height: 45px;
                           color: #fff;
                           width: 145px;
                           text-align: center;
                           padding-right: 6px;
                           padding-left: 6px;"
                    >
                        Edit / Save
                    </button>
                </div>
                <div
                    class="modal fade"
                    id="changePasswordModal"
                    tabindex="-1"
                    role="dialog"
                    aria-labelledby="changePasswordLabel"
                    aria-hidden="true"
                >
                    <div
                        class="modal-dialog modal-dialog-centered"
                        role="document"
                    >
                        <div class="modal-content">
                            {% include 'includes/password_change_form.html'%}
                        </div>
                    </div>
                </div>

                <div
                    class="modal fade"
                    id="exampleModal"
                    tabindex="-1"
                    role="dialog"
                    aria-labelledby="exampleModalLabel"
                    aria-hidden="true"
                >
                    <div
                        class="modal-dialog modal-dialog-centered"
                        role="document"
                    >
                        <div class="modal-content">
                            {% include 'includes/edit_profile_form.html' %}
                        </div>
                    </div>
                </div>
            </div>
        </div>

        {% endblock %} {% block javascript%}
        <script type="text/javascript">
            document
                .getElementsByName("avatar")[0]
                .addEventListener("change", doThing);

            function getBase64(file) {
                return new Promise((resolve, reject) => {
                    const reader = new FileReader();
                    reader.readAsDataURL(file);
                    reader.onload = () => resolve(reader.result);
                    reader.onerror = error => reject(error);
                });
            }

            async function doThing(event) {
                const file = event.target.files[0];
                const result = await getBase64(file);

                document.getElementsByName("suka_avatar")[0].src = result;

                console.log(document.getElementsByName("suka_avatar")[0]);
            }
            $(function() {
                var saveFormPasswordChange = function() {
                    var form = $(this);
                    $.ajax({
                        url: form.attr("action"),
                        data: form.serialize(),
                        type: form.attr("method"),
                        dataType: "json",
                        success: function(data) {
                            if (data.form_is_valid) {
                                location.reload();
                            } else {
                                $("#changePasswordModal .modal-content").html(
                                    data.html_form
                                );
                            }
                        }
                    });
                    return false;
                };
                var saveFormEditProfile = function() {
                    var form = $("#formEditProfile");
                    var formData = new FormData();
                    formData.append(
                        "avatar",
                        $("input[type=file]")[0].files[0]
                    );
                    formData.append(
                        "csrfmiddlewaretoken",
                        $("#formEditProfile input[type=hidden]").val()
                    );
                    formData.append("name", $("#id_name").val());
                    formData.append("email", $("#id_email").val());
                    $.ajax({
                        url: form.attr("action"),
                        data: formData,
                        type: form.attr("method"),
                        cache: false,
                        contentType: false,
                        processData: false,
                        success: function(data) {
                            if (data.form_is_valid) {
                                location.reload();
                            } else {
                                $("#exampleModal .modal-content").html(
                                    data.html_form
                                );
                            }
                        }
                    });
                    return false;
                };
                $("#changePasswordModal").on(
                    "submit",
                    ".js-change-password",
                    saveFormPasswordChange
                );
                $("#exampleModal").on(
                    "submit",
                    ".js-edit-profile",
                    saveFormEditProfile
                );
            });
        </script>
        {% endblock %}
    </div>
</div>